AllCops:
  EnabledByDefault: true

  Exclude:
    - 'bin/tapioca'
    - 'lib/**/*.tab.rb'
    - 'csv_plus_plus.gemspec'

  # TODO lower this (no need to be fancy really) 
  TargetRubyVersion: 3.1

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*_spec.rb'
